# Generated by Django 4.0.4 on 2022-05-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='school_name',
        ),
    ]
