# Generated by Django 4.0.4 on 2022-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_remove_quote_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='quote',
            name='school_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
