# Generated by Django 4.0.4 on 2022-05-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0006_quote_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='pdf_file',
        ),
    ]
