# Generated by Django 4.0.4 on 2022-05-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0007_remove_quote_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quote',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
