# Generated by Django 4.0.4 on 2022-05-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0009_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
