# Generated by Django 4.0.4 on 2022-05-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0010_delete_document_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('invoice_no', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=256)),
                ('to_name', models.CharField(max_length=256)),
                ('school_address', models.CharField(max_length=2048)),
                ('school_country', models.CharField(max_length=256)),
                ('to_email', models.EmailField(max_length=254)),
                ('school_size', models.IntegerField()),
                ('price_per_student', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('bank_detail', models.CharField(blank=True, max_length=2048)),
                ('pdf_file', models.FileField(null=True, upload_to='quotes/')),
                ('special_comments', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
