# Generated by Django 4.0.4 on 2022-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0011_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quotes/'),
        ),
    ]
