# Generated by Django 4.0.4 on 2022-05-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0013_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='invoice_no',
            field=models.CharField(default='', max_length=16),
        ),
    ]
