# Generated by Django 4.0.4 on 2022-05-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0014_alter_quote_invoice_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
