# Generated by Django 4.0.4 on 2022-05-27 10:01

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0017_alter_quote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='pdf_file',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
